Zm 01 add room
N1ghtStalk3r/ARTIC pull request #14
Opened 2022-11-10 19:08 UTC by Zimaxim

Состав изменений:
1. В проект добавлен Room. Теперь в базе данных - artic хранятся данные о купленных билетах.
2. Изменен логотип приложения. 
3. В форму "Билет" добавлены 
 3.1. создание нового события в календаре Google.
 3.2. удаление билета из таблицы tickets.
4. Упрощен процесс формирования QR-кода 
5. Исправлена ошибка "пустой список билетов"

2022-11-10 20:59 UTC, NLCodeTeam requested changes

2022-11-10 20:59 UTC, NLCodeTeam commented on app/src/main/java/com/nightstalker/artic/MainActivity.kt
> +        intent.type = "vnd.android.cursor.item/event"
вынести в константы

2022-11-10 20:59 UTC, NLCodeTeam commented on app/src/main/java/com/nightstalker/artic/MainActivity.kt
> +                it.first == "beginTime" -> intent.putExtra(it.first, calendarEvent.timeInMillis + it.second.toInt())
тоже самое и что значит это условие вообще?

2022-11-10 20:59 UTC, NLCodeTeam commented on app/src/main/java/com/nightstalker/artic/features/MappersExt.kt
> +        title = title?:"",
между операторами нужны пробелы одиночные

2022-11-10 20:59 UTC, NLCodeTeam commented on app/src/main/java/com/nightstalker/artic/features/MappersExt.kt
> +    listOf(
что это за список такой ?

2022-11-10 20:59 UTC, NLCodeTeam commented on app/src/main/java/com/nightstalker/artic/features/artwork/presentation/ui/list/ArtworksListFragment.kt
> +        binding?.searchView?.setOnQueryTextListener(object : SearchView.OnQueryTextListener {
писал, чтобы вы уже наконец сделали extension функцию ,чтобы каждый раз такие куски кода не писать тут одинаковые

2022-11-10 20:59 UTC, NLCodeTeam commented on app/src/main/java/com/nightstalker/artic/features/artwork/presentation/ui/list/ArtworksListFragment.kt
> +        binding?.searchView?.setOnQueryTextListener(object : SearchView.OnQueryTextListener {
один в один просто

2022-11-10 20:59 UTC, NLCodeTeam commented on app/src/main/java/com/nightstalker/artic/features/qrcode/QRCodeGenerator.kt
> +    private lateinit var _state: Exhibition
миллион раз уже сказали переписать класс, даже было обсуждение в группе что с ним не так

2022-11-10 20:59 UTC, NLCodeTeam commented on app/src/main/java/com/nightstalker/artic/features/qrcode/QrCodeGenerator.kt
> +class QrCodeGenerator {
чем этот генератор отличается от того ?

2022-11-10 20:59 UTC, NLCodeTeam commented on app/src/main/java/com/nightstalker/artic/features/ticket/presentation/ui/detail/TicketDetailsFragment.kt
> +        }
посмотри на все что выше - как ты думаешь это хороший стиль кода? что можно из него понять ?

2022-11-11 08:45 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/MainActivity.kt
> +                it.first == "beginTime" -> intent.putExtra(it.first, calendarEvent.timeInMillis + it.second.toInt())
Что значат beginTime, endTime и allDay? Почему это строки? Почему для begin и end одинаковые строки выполняются?

2022-11-11 08:45 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/MainActivity.kt
> +        intent.type = "vnd.android.cursor.item/event"
в strings

2022-11-11 08:45 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/core/local/ticket/LocalTicket.kt
> +@Entity(tableName = "tickets",
tableName вынести в константу и переиспользовать везде, где с ней работаешь

2022-11-11 08:45 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/core/local/ticket/TicketDao.kt
> +    @Query("DELETE FROM tickets WHERE id = :ticketId OR exhibition_id = :exhibitionId ")
Например тут tickets должен быть константой. Чтобы точно нигде не ошибиться в написании

2022-11-11 08:45 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/features/MappersExt.kt
> +        title = title?:"",
Ко всем файлам, перед отправкой на проверку надо прожимать "Ctrl+Alt+L" чтобы приводить в соответствие со стилем кода проекта.

2022-11-11 08:45 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/features/ticket/presentation/ui/detail/TicketDetailsFragment.kt
> +    private var exhibition_id = -1  // заполняется в ExhibitionDetailsFragment
Сделай их nullable

2022-11-11 08:45 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/features/ticket/presentation/ui/detail/TicketDetailsFragment.kt
> +        when {
Это не нужно

2022-11-11 08:45 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/features/ticket/presentation/ui/detail/TicketDetailsFragment.kt
> +        exhibition_id = arguments?.getInt("ExhibitionId")?:-1
А тут просто:
`exhibition_id = arguments?.getInt("ExhibitionId")?.let { 
    exhibitionsViewModel.getExhibition(exhibition_id)
    initExhibitionObserver()
}`
`ticket_id = args.ticketId.toLong()?.let {
    ticketsViewModel.getTicket(ticket_id)
    initTicketObserver()
}`

2022-11-11 08:45 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/features/ticket/presentation/ui/detail/TicketDetailsFragment.kt
> +    private var binding: FragmentTicketDetailsBinding? = null
используй lateinit вместо nullable binding

2022-11-14 09:28 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/MainActivity.kt
> +            when {
`when(it.key)` - ты же все время it.key сравниваешь

2022-11-14 09:30 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/MainActivity.kt
> +                    "beginTime",
begin, end и all все еще почему-то не константы. И не надо тут список делать. Тем более что в следующей строке у тебя список из одного элемента.
Ты мог бы написать` "beginTime", "endTime" -> ....` но используй константы(!)

2022-11-14 09:33 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/features/MappersExt.kt
> +    "beginTime" to aicStartAt
Вот еще одно место, где должны были быть эти константы

2022-11-14 09:33 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/features/artwork/presentation/ui/ArtworkViewModel.kt
> +            delay(1000)
Зачем задержка?

2022-11-14 09:36 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/features/artwork/presentation/ui/dialog/FilterArtworksBottomSheetDialog.kt
> +        applyForTextView(placesAdapter, this!!.countries, Color.GREEN)
Не используем `!!`

2022-11-14 09:37 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/features/artwork/presentation/ui/dialog/FilterArtworksBottomSheetDialog.kt
> +        this?.countries?.addTextChangedListener {
Если бы binding был lateinit, то не пришлось бы каждый раз писать `this?.`

2022-11-14 09:38 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/features/qrcode/QRScannerFragment.kt
> +    //
Забыл убрать

2022-11-14 09:38 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/features/qrcode/QRScannerFragment.kt
> +        Toast.makeText(context!!, rawResult?.contents, Toast.LENGTH_LONG).show()
Не используем `!!`

2022-11-14 09:39 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/features/ticket/presentation/ui/detail/TicketDetailsFragment.kt
> +            exhibition_id!! > 0 -> {
Не используем `!!`

2022-11-14 09:41 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/features/ticket/presentation/ui/detail/TicketDetailsFragment.kt
> +                exhibitionsViewModel.getExhibition(exhibition_id!!)
Что мешало эти строки добавить в строки 55 и 56 как apply? это же должно произойти только если у тебя в аргументах есть хоть что-то и это > 0

2022-11-14 09:43 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/MainActivity.kt
> +        intent.type = "vnd.android.cursor.item/event"
Все еще не в строках

2022-11-15 11:39 UTC, Zimaxim commented on app/src/main/java/com/nightstalker/artic/MainActivity.kt
> +        intent.type = "vnd.android.cursor.item/event"
В origin/ZM-01_add_room  вроде как должно быть.

2022-11-15 11:39 UTC, Zimaxim commented on app/src/main/java/com/nightstalker/artic/MainActivity.kt
> +                it.first == "beginTime" -> intent.putExtra(it.first, calendarEvent.timeInMillis + it.second.toInt())
// Период работы выставки, Long параметры
                it.key in listOf(EVENT_BEGIN, EVENT_END) -> intent.putExtra(
                    it.key,
                    it.value.toLong()
                )

2022-11-15 11:43 UTC, Zimaxim commented on app/src/main/java/com/nightstalker/artic/features/MappersExt.kt
> +    listOf(
Для подготовки события в календаре надо заполнить из реквизитов TicketUseCase несколько параметров. 
Теперь эти параметры представлены fun TicketUseCase.toCalendarEvent(): Map<String, String>

2022-11-15 11:47 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/features/artwork/presentation/ui/dialog/FilterArtworksBottomSheetDialog.kt
> +                putString("place", this.countries.text.toString())
Это что за строки? Почему не константы? Стараемся не использовать строки в коде. Это должны быть либо константы, либо вытаскиваться из строковых ресурсов. Допускаются исключения в логах

2022-11-15 11:47 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/features/artwork/presentation/ui/list/ArtworksListFragment.kt
> +            val string1 = getString("place")?.apply {
Те же константы

2022-11-15 11:48 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/features/exhibition/presentation/ui/detail/ExhibitionDetailsFragment.kt
> +            bundle.putInt("ExhibitionId", args.exhibitionId)
константа

2022-11-15 11:49 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/features/qrcode/QRScannerFragment.kt
> +            scannerView.setBorderStrokeWidth(10)
Magic numbers
Тоже хорошо бы в константу

2022-11-15 11:57 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/features/ticket/presentation/ui/detail/TicketDetailsFragment.kt
> +        when {
```
arguments?.getInt("ExhibitionId")?.let {
    if (it > 0) {  //если это условие вообще нужно
        exhibitionsViewModel.getExhibition(exhibition_id)
        initExhibitionObserver()
    }
} ?: DEFAULT_EXHIBITION_ID
```

2022-11-15 11:58 UTC, Diwixi commented on app/src/main/java/com/nightstalker/artic/network/net/ArtworksApi.kt
> +const val TYPE = "type"
так вот же эти константы, которые не используются почему-то

2022-11-15 12:02 UTC, Zimaxim commented on app/src/main/java/com/nightstalker/artic/features/qrcode/QRScannerFragment.kt
> +    //
Убрали

2022-11-15 13:25 UTC, Zimaxim commented on app/src/main/java/com/nightstalker/artic/features/artwork/presentation/ui/list/ArtworksListFragment.kt
> +        binding?.searchView?.setOnQueryTextListener(object : SearchView.OnQueryTextListener {
[ArtworksListFragment.kt оптимизирован: дубли кода удалены

2022-11-15 13:26 UTC, Zimaxim commented on app/src/main/java/com/nightstalker/artic/features/qrcode/QRCodeGenerator.kt
> +    private lateinit var _state: Exhibition
Все ссылки на Exhibition из класса удалены

2022-11-15 13:26 UTC, Zimaxim commented on app/src/main/java/com/nightstalker/artic/features/qrcode/QrCodeGenerator.kt
> +class QrCodeGenerator {
Дубль кода  удален.

2022-11-15 13:28 UTC, Zimaxim commented on app/src/main/java/com/nightstalker/artic/features/ticket/presentation/ui/detail/TicketDetailsFragment.kt
> +        }
Удаление текущего билета из таблицы билетов и возвращение в список билетов.

2022-11-15 19:03 UTC, Zimaxim commented on app/src/main/java/com/nightstalker/artic/features/artwork/presentation/ui/ArtworkViewModel.kt
> +            .debounce(1000)
TIMEOUT_1000

2022-11-15 19:04 UTC, Zimaxim commented on app/src/main/java/com/nightstalker/artic/features/exhibition/presentation/ui/detail/ExhibitionDetailsFragment.kt
> +            bundle.putInt("ExhibitionId", args.exhibitionId)
BUNDLE_EXHIBITION_ID

2022-11-15 19:06 UTC, Zimaxim commented on app/src/main/java/com/nightstalker/artic/features/artwork/presentation/ui/list/ArtworksListFragment.kt
> +            val string1 = getString("place")?.apply {
ARGS_PLACE

2022-11-15 19:08 UTC, Zimaxim commented on app/src/main/java/com/nightstalker/artic/features/artwork/presentation/ui/dialog/FilterArtworksBottomSheetDialog.kt
> +                putString("place", this.countries.text.toString())
ARGS_PLACE

2022-11-19 17:58 UTC, closed without merging